import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import ImageComponent from './components/ImageComponent'

export default function Home() {
	const [photos, setPhotos] = useState([])

	const key = 'f301fdef5502a7cb0f561598b32a3691' // Flickr acces key

	const getData = tag => {
		tag.target.value
	}
	let setSearchTag = getData()

	const [value, setValue] = useState('')

	const handleEnter = e => {
		if (e.key === 'Enter') {
			return handleSubmit(value)
		}
	}

	const getPhotoRequest = async () => {
		const url = `https://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=${key}&tags=${setSearchTag}&per_page=100&page=1&format=json&nojsoncallback=1`

		const response = await fetch(url)
		const data = await response.json()

		console.log(data.photos.photo)
		setPhotos(data.photos.photo)
	}

	useEffect(data => {
		getPhotoRequest(data)
	}, [])

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<form>
					<input
						id="userInput"
						type="text"
						placeholder="Search.."
						onChange={getData}
						// onKeyDown={handleEnter}
						// value={value}
					></input>
					<button type="submit" onClick={() => handleSubmit(value)}>
						Search
					</button>
				</form>
			</header>

			<p id="reminder"></p>

			<main className={styles.main}>
				<ImageComponent photos={photos} />
			</main>
		</div>
	)
}
