import Head from 'next/head'
// import '/styles/globals.css'
import React, { useState, useEffect } from 'react'
import ImageComponent from './components/ImageComponent'

export default function Home() {
	const [photos, setPhotos] = useState([])
	const key = 'f301fdef5502a7cb0f561598b32a3691' // Flickr acces key
	const [searchValue, setSearchValue] = useState('Sport') // Set the Default to Sport

	const handleButtonClick = () => {
		let inputValue = document.getElementById('userInput') // input field
		setSearchValue(inputValue.value)
	}

	let setSearchTag = searchValue // Refers to the user input

	const getPhotoRequest = async () => {
		const url = `https://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=${key}&tags=${setSearchTag}&per_page=100&page=1&format=json&nojsoncallback=1`

		const response = await fetch(url)
		const data = await response.json()

		setPhotos(data.photos.photo)
	}

	useEffect(
		data => {
			getPhotoRequest(data)
		},
		[searchValue] // occures when the user clicks on button
	)

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<input id="userInput" type="text" placeholder="Search.."></input>
				<button onClick={handleButtonClick}>Search</button>
				<h2>
					<span>Results for:</span> {searchValue}
				</h2>
			</header>

			<main>
				<ImageComponent photos={photos} />
			</main>
		</div>
	)
}
